
-- Remove legacy tables and add Rental performance indexes
-- Generated by cleanup-legacy-migration.ts

-- Drop image tables first (they have foreign keys)
DROP TABLE IF EXISTS "PropertyImage";
DROP TABLE IF EXISTS "UnitImage"; 
DROP TABLE IF EXISTS "ListingImage";

-- Drop main legacy tables
DROP TABLE IF EXISTS "Listing";
DROP TABLE IF EXISTS "Unit";
DROP TABLE IF EXISTS "Property";

-- Add performance indexes to Rental table
CREATE INDEX IF NOT EXISTS "idx_rental_property_type" ON "Rental"("propertyType");
CREATE INDEX IF NOT EXISTS "idx_rental_status" ON "Rental"("status");
CREATE INDEX IF NOT EXISTS "idx_rental_price" ON "Rental"("price");
CREATE INDEX IF NOT EXISTS "idx_rental_location" ON "Rental"("city", "state");
CREATE INDEX IF NOT EXISTS "idx_rental_created_at" ON "Rental"("createdAt");
CREATE INDEX IF NOT EXISTS "idx_rental_user_id" ON "Rental"("userId");

-- Add composite indexes for common queries
CREATE INDEX IF NOT EXISTS "idx_rental_search" ON "Rental"("propertyType", "status", "price");
CREATE INDEX IF NOT EXISTS "idx_rental_location_search" ON "Rental"("city", "state", "propertyType", "status");
