name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Run security scans weekly
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Scan backend dependencies
    - name: Scan backend dependencies
      uses: snyk/actions/node@master
      with:
        args: --all-projects
        command: test
        json: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
    
    # CodeQL Analysis for JavaScript/TypeScript code
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript, typescript
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    
    # OWASP ZAP Scan (Uncomment when API endpoints are defined)
    # - name: ZAP Scan
    #   uses: zaproxy/action-baseline@v0.11.0
    #   with:
    #     target: 'https://staging-api.propertyai.example.com'
    
    # Docker image scanning (Uncomment when Docker is used)
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: 'propertyai-backend:latest'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL,HIGH'
    
    # Secret scanning
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.63.7
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified
      continue-on-error: true
    
    # Generate and upload security report
    - name: Generate Security Report
      run: |
        echo "# Security Scan Report" > security-report.md
        echo "## Scan Date: $(date)" >> security-report.md
        echo "## Repository: ${{ github.repository }}" >> security-report.md
        echo "## Commit: ${{ github.sha }}" >> security-report.md
        echo "\n*Detailed reports available in CI logs*" >> security-report.md
    
    - name: Upload Security Report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.md 